app = "$APPNAME"
[build]
  dockerfile = "Dockerfile"
[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_start = true
  auto_stop = false
  [[services.ports]]
    handlers = ["http"]
    port = 80
